"""Document generation: ICS calendar invites, Markdown/HTML itineraries,
briefs, RFQ emails and application cover notes — pure Python."""
from __future__ import annotations

import html
import uuid
from datetime import datetime, timedelta


def _ics_dt(s: str | None, fallback: datetime) -> str:
    try:
        d = datetime.strptime(s[:16], "%Y-%m-%d %H:%M") if s and len(s) >= 16 else datetime.strptime(s[:10], "%Y-%m-%d")
    except Exception:
        d = fallback
    return d.strftime("%Y%m%dT%H%M%S")


def ics(events: list[dict]) -> str:
    lines = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//COMPASS//Decision Engine//EN", "CALSCALE:GREGORIAN"]
    now = datetime.utcnow()
    for e in events:
        start = e.get("start")
        end = e.get("end")
        st = _ics_dt(start, now + timedelta(days=1))
        en = _ics_dt(end, now + timedelta(days=1, hours=1))
        lines += ["BEGIN:VEVENT", f"UID:{uuid.uuid4()}@compass", f"DTSTAMP:{now.strftime('%Y%m%dT%H%M%SZ')}",
                  f"DTSTART:{st}", f"DTEND:{en}", f"SUMMARY:{e.get('title', 'COMPASS event')}",
                  f"DESCRIPTION:{(e.get('description') or '').replace(chr(10), ' ')[:900]}",
                  f"LOCATION:{e.get('location', '')}", "END:VEVENT"]
    lines.append("END:VCALENDAR")
    return "\r\n".join(lines)


def money(v) -> str:
    return f"${v:,.0f}" if isinstance(v, (int, float)) else "—"


def markdown_report(title: str, prompt: str, rationale: str, rows: list[dict], conf: float, extra: list[str] | None = None) -> str:
    out = [f"# {title}", "", f"> {prompt}", "", f"**Confidence:** {conf:.0%}", "", f"**Why #1:** {rationale}", "",
           "| # | Option | Price | Score | Verified | Sources |", "|---|---|---|---|---|---|"]
    for i, r in enumerate(rows[:8], 1):
        out.append(f"| {i} | {r['title']} | {money(r.get('price'))} | {r.get('score', 0):.3f} | {'✅' if r.get('verified') else '⚠️'} | "
                   f"{', '.join(r.get('sources', [])[:3])} |")
    if extra:
        out += ["", *extra]
    out += ["", f"_Generated by COMPASS · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}_"]
    return "\n".join(out)


def md_to_html(md: str) -> str:
    rows = []
    for line in md.splitlines():
        e = html.escape(line)
        if line.startswith("# "):
            rows.append(f"<h2>{html.escape(line[2:])}</h2>")
        elif line.startswith("|") and "---" not in line:
            cells = "".join(f"<td style='padding:4px 8px;border:1px solid #ddd'>{html.escape(c.strip())}</td>" for c in line.strip("|").split("|"))
            rows.append(f"<tr>{cells}</tr>")
        elif line.startswith("> "):
            rows.append(f"<blockquote>{html.escape(line[2:])}</blockquote>")
        elif line.strip():
            rows.append(f"<p>{e.replace('**', '')}</p>")
    body = "".join(rows)
    body = body.replace("<tr>", "<table style='border-collapse:collapse'><tr>", 1)
    if "<table" in body:
        idx = body.rfind("</tr>")
        body = body[: idx + 5] + "</table>" + body[idx + 5:]
    return f"<div style='font-family:system-ui'>{body}</div>"


def rfq_email(product: str, quantity: int, supplier: dict, buyer: str = "Procurement Team") -> dict:
    subj = f"RFQ: {quantity:,} units — {product}"
    body = (f"Hello {supplier.get('source') or 'team'},\n\n"
            f"We are evaluating suppliers for {quantity:,} units of {product}. Based on your listing "
            f"({supplier.get('url') or 'your catalog'}) quoting around {money(supplier.get('price'))}/unit"
            f"{' with MOQ ' + str(int(supplier['attributes']['moq'])) if (supplier.get('attributes') or {}).get('moq') else ''}, "
            f"please send:\n"
            f"  1. Tiered unit pricing at {quantity:,} / {quantity * 2:,} / {quantity * 5:,} units (FOB & DDP)\n"
            f"  2. Confirmed MOQ and lead time\n  3. Certifications (CE / FCC / RoHS / Bluetooth SIG)\n"
            f"  4. Sample availability and cost\n  5. Payment terms and warranty / defect policy\n\n"
            f"Please reply within 5 business days.\n\nBest regards,\n{buyer}")
    return {"subject": subj, "body": body}


def cover_note(job: dict) -> str:
    a = job.get("attributes") or {}
    return (f"Dear {a.get('company', 'Hiring')} team,\n\nI'm excited to apply for the {job.get('title', '').split(' · ')[0]} role"
            f"{' (' + a['location'] + ')' if a.get('location') else ''}. My background in building production React/TypeScript "
            f"products maps directly to this position, and I'd love to contribute to {a.get('company', 'your team')}'s roadmap.\n\n"
            f"Thank you for your consideration.")
